export const enum ORDER_STATUS_ID {
  ORDER_NOT_READY = 1,
  ORDER_ROUTE_CREATED = 2,
  ORDER_READY = 4,
  ORDER_COMPLETED = 5,
  ORDER_REFUNDED = 11,
  ORDER_RETURNED = 14,
  ORDER_CANCELLED = 17,
  ORDER_IN_TRANSIT = 21,
  ORDER_IN_DELIVERY = 23,
  DRIVER_PHONE = '-'
}
